In [1]:
import math
import collections

import numpy as np
import pandas as pd
import matplotlib.pyplot as pp

%matplotlib inline

In [3]:
fromlist = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
fromlist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
fromlist.shape

(3, 3)

In [11]:
fromlist3d = np.array([[[1,2,3, 0],[4,5,6, 0],[7,8,9, 0]],
                       [[10,11,12, 0], [10,11,12, 0], [10,11,12, 0]]])

In [12]:
fromlist3d.shape

(2, 3, 4)

In [13]:
# rand_2d = np.random.random(size=(8,8))
# np.save('random.npy', rand_2d)
# np.savetxt('random.txt', rand_2d)
# open('random.txt', 'r').readlines()

np.save('my3dlist.npy', fromlist3d)

In [15]:
# np.savetxt('my3dlist.txt', fromlist3d)
np.savetxt('my3dlist.txt', fromlist3d.reshape(2, 12), fmt='%d')


1 2 3 0 4 5 6 0 7 8 9 0
10 11 12 0 10 11 12 0 10 11 12 0


In [16]:
open('my3dlist.txt', 'r').readlines()

['1 2 3 0 4 5 6 0 7 8 9 0\n', '10 11 12 0 10 11 12 0 10 11 12 0\n']

In [26]:
linear = np.linspace(0, 9, 10)
linear

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
linear.shape

(5,)

In [27]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])